version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: guitar-tuner-nginx
    restart: unless-stopped
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - guitar-tuner_logs:/var/log/nginx
    environment:
      - TZ=Europe/Kiev
    networks:
      - traefik_web-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.guitar-tuner.rule=Host(`guitar-tuner.perek.rest`)"
      - "traefik.http.routers.guitar-tuner.entrypoints=websecure"
      - "traefik.http.routers.guitar-tuner.tls=true"
      - "traefik.http.routers.guitar-tuner.tls.certresolver=myresolver"
      - "traefik.http.services.guitar-tuner.loadbalancer.server.port=80"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  guitar-tuner_logs:

networks:
  traefik_web-network:
    external: true